feat: init user api crud endpoints
vladpalkanov/hrjs22 pull request #10
Opened 2024-11-28 00:05 UTC by rcinos

Basic crud endpoints were created without authorization with JWT tokens and admin priviledges

2024-11-28 18:37 UTC, vladpalkanov requested changes

2024-11-28 18:37 UTC, vladpalkanov commented on apps/user/src/user.service.ts
> +    id: crypto.randomUUID(),
mongoose creates id

2024-11-28 18:39 UTC, rcinos commented on apps/user/src/user.service.ts
> +    id: crypto.randomUUID(),
should i use its default _id or create it with mongoose

2024-11-28 19:09 UTC, vladpalkanov commented on apps/user/src/user.service.ts
> +    id: crypto.randomUUID(),
use auto-generated _id

2024-11-29 08:36 UTC, rcinos commented on apps/user/src/utils/errors.ts
> +  get name() {
As it extends from Error I have to follow it methods, and name there is a getter

2024-11-29 09:14 UTC, vladpalkanov requested changes

2024-11-29 09:14 UTC, vladpalkanov commented on apps/user/src/utils/errors.ts
> +  get name() {
I have not found any info that proves `Error.prototype.name` is a getter. But even if it is, in case you extend your custom error class with `Error` and define property `name` it would be own property. That means any address to this own property will take it from the custom error instance.

2024-11-29 09:20 UTC, rcinos commented on apps/user/src/utils/errors.ts
> +  get name() {
sorry, I thought it was a getter, but it is just a simpley property

2024-11-29 09:30 UTC, vladpalkanov approved these changes

2024-11-29 09:32 UTC, merged